#1512 Added selectWoo to Change Entry Creator
gravityview/GravityView pull request #1523
Opened 2020-10-27 12:04 UTC by shamalisulakhe

Added selectWoo ajax for 'change entry creator' feature.
Required selectWoo files are added at assets/lib/selectWoo

2020-10-27 12:35 UTC, mrcasual commented on includes/class-gravityview-change-entry-creator.php
> +        $search_string = isset( $_POST['q'] ) ? $_POST['q'] : '';
@shamalisulakhe  you can use `[rgpost](https://docs.gravityforms.com/rgpost/)` helper function.

2020-10-27 12:41 UTC, zackkatz reviewed
Styling issue with Safari + Gravity Forms 2.5:
![](https://i.gravityview.co/I7uXQE+)

2020-10-27 12:41 UTC, zackkatz commented on includes/class-gravityview-change-entry-creator.php
> +        $search_string = isset( $_POST['q'] ) ? $_POST['q'] : '';
@shamalisulakhe should use $post_var

2020-10-27 12:41 UTC, zackkatz commented on assets/js/admin-entry-creator.js
> +            // escapeMarkup: function (markup) { return markup; }, // let our custom formatter work
I assume this isn't needed

2020-10-27 12:41 UTC, zackkatz commented on assets/js/admin-entry-creator.js
> +	$(document).ready(function(){
Please apply formatting to all the files

2020-10-27 12:41 UTC, zackkatz commented on includes/class-gravityview-change-entry-creator.php
> +        echo json_encode( $users );
Let's use `wp_send_json( $users, 200 );` instead. That uses `wp_json_encode()` and passes the right headers if not sent.

2020-10-27 12:49 UTC, zackkatz commented on includes/class-gravityview-change-entry-creator.php
> +            'search_columns' => array( 'user_login', 'user_email', 'user_nicename', 'display_name' ),
Let's add `ID` in here; a user might want to search by ID.

2020-10-27 12:49 UTC, zackkatz commented on includes/class-gravityview-change-entry-creator.php
> +        $search_string = isset( $_POST['q'] ) ? $_POST['q'] : '';
Since you're parsing and sanitizing `$_POST` already, `rgar()` would work

2020-10-27 12:49 UTC, zackkatz commented on includes/class-gravityview-change-entry-creator.php
> +            'search'         => '*' . $search_string . '*',
If searching by ID, `$search_string` would be numeric. If numeric, let's make it wildcard only after the search: `$search_string . '*'`

2020-10-27 12:49 UTC, zackkatz commented on assets/js/admin-entry-creator.js
> + * @since 1.0.0
We generally put either `@since TODO` or `@since [whatever minor version is upcoming]`

2020-10-27 12:53 UTC, zackkatz requested changes
I would like to show a default dropdown of users in addition to the JS search. 

Seeing no options is a bit jarring for me: 
![](https://i.gravityview.co/f6n2NC+)

Instead, when clicking the selectWoo instance, I'd like to see a list of users.

2020-10-27 12:58 UTC, shamalisulakhe commented on includes/class-gravityview-change-entry-creator.php
> +        $search_string = isset( $_POST['q'] ) ? $_POST['q'] : '';
Changed it to use post_var

2020-10-27 13:04 UTC, shamalisulakhe commented on assets/js/admin-entry-creator.js
> + * @since 1.0.0
Okay @zackkatz Which version should be put in @since comment?

2020-10-27 13:09 UTC, shamalisulakhe commented on assets/js/admin-entry-creator.js
> +            // escapeMarkup: function (markup) { return markup; }, // let our custom formatter work
Okay, removed it.

2020-10-27 13:09 UTC, shamalisulakhe commented on includes/class-gravityview-change-entry-creator.php
> +        echo json_encode( $users );
Done

2020-10-27 13:09 UTC, shamalisulakhe commented on includes/class-gravityview-change-entry-creator.php
> +            'search_columns' => array( 'user_login', 'user_email', 'user_nicename', 'display_name' ),
Done

2020-10-27 13:14 UTC, zackkatz commented on includes/class-gravityview-change-entry-creator.php
> -            'search'         => '*' . $search_string . '*',
@shamalisulakhe I only wanted the look-ahead wildcard for the ID field, not for everything.

Please re-read what I wrote about my reasoning there. Let me know if you have thoughts about that.

2020-10-27 13:17 UTC, shamalisulakhe commented
@zackkatz 
As you said that you would like to show a default dropdown of users in addition to the JS search.
Should the default no. users be trimmed to a specific number, say 100 or so? It will reduce checking the need for checking the no. of users (as was there is previous version of code)?

2020-10-27 13:24 UTC, zackkatz commented
> @zackkatz
> As you said that you would like to show a default dropdown of users in addition to the JS search.
> Should the default no. users be trimmed to a specific number, say 100 or so? It will reduce checking the need for checking the no. of users (as was there is previous version of code)?

Yes, let's trim to 100.

And please deprecate the existing filter using `apply_filters_deprecated()`.

2020-10-28 16:12 UTC, shamalisulakhe reviewed
> > @zackkatz
> > As you said that you would like to show a default dropdown of users in addition to the JS search.
> > Should the default no. users be trimmed to a specific number, say 100 or so? It will reduce checking the need for checking the no. of users (as was there is previous version of code)?
> 
> @shamalisulakhe Yes, let's trim to 100.
> 
> And please deprecate the existing filter using `apply_filters_deprecated()`.

@zackkatz Added default options (100) on load, but I referred to some select2 issues and got to know that showing default options doesn't work if _minimumInputLength_ is specified. Thus, I had to disable _minimumInputLength_ which was set to 3 before. I am still looking if such issues are resolved anywhere.

2020-10-28 16:18 UTC, zackkatz commented
> @zackkatz Just a question, might there be any chances that a user would search by numeric keyword and might be looking for results matching other fields, say email address? Because email addresses also have numbers.

@shamalisulakhe Yes, emails have numbers. I was going to keep what you have until we get a user report of an issue.

2020-10-28 18:52 UTC, zackkatz commented on assets/js/admin-entry-creator.js
> + * @since 1.0.0
@shamalisulakhe Ideally, I want you to decide these things once I provide feedback. Either one would have been good. `@since TODO` is fine.

2020-10-29 06:03 UTC, shamalisulakhe commented on assets/js/admin-entry-creator.js
> + * @since 1.0.0
Okay, I wasn't knowing of putting TODO in since comment, thus wanted to confirm. Thanks!

2020-10-29 17:55 UTC, shamalisulakhe commented
> And please deprecate the existing filter using `apply_filters_deprecated()`.

 @zackkatz I found two filters are applied in GVComman::get_users() that fetches users for the dropdown.

> 
> /**
>  * @filter gravityview/get_users/{$context} There are issues with too many users using [get_users()](http://codex.wordpress.org/Function_Reference/get_users) where it breaks the select. We try to keep it at a reasonable number. \n
>  * $context is where are we using this information (e.g. change_entry_creator, search_widget ..)
>  * @param array $settings Settings array, with number key defining the # of users to display
>  */
> $get_users_settings = apply_filters( 'gravityview/get_users/'. $context, apply_filters( 'gravityview_change_entry_creator_user_parameters', $get_users_settings ) );

Just to confirm, I have depracated '_gravityview_change_entry_creator_user_parameters_' filter, as '_gravityview/get_users/'. $context_ may be called in another context. Let me know if I get it right.

2020-12-04 01:25 UTC, zackkatz approved these changes

2020-12-04 01:26 UTC, merged