Allow customizing labels in Edit Entry
gravityview/GravityView pull request #1609
Opened 2021-06-08 00:04 UTC by zackkatz

Go to a View's Edit Entry settings. You'll see two new settings:

- Cancel Link Text
- Update Button Text

Go to Delete Entry settings. You'll see a new setting.

- Delete Link Text

For each button, test:

- [ ] HTML is not allowed (gets sanitized)
- [ ] Emoji in settings do work
- [ ] Existing Views still have default button text
- [ ] Settings save properly
- [ ] Code looks good (for @mrcasual )

*Note: There are also hidden settings "Next Page Button Text" and "Previous Page Button Text" related to multi-page forms that will not be shown in the UI yet but exist, ready to be translated.*

2021-06-08 00:26 UTC, rafaehlers commented
Tests good ✔️ 
Only thing missing from #1556 is the `Always go back to previous page` for the cancel button

2021-06-08 07:25 UTC, crbdev reviewed
✔ All good from my end!

2021-06-14 21:01 UTC, mrcasual approved these changes

2021-06-15 16:56 UTC, bennemann requested changes
It works great! However, it isn't processing Merge Tags on the custom label (although it's clearly an option at the input):

![image](https://user-images.githubusercontent.com/5726194/122093216-21aed480-ce0b-11eb-826e-6d96405f5c52.png)

2021-07-12 18:56 UTC, merged