upgrade fancybox
gravityview/GravityView pull request #1639
Opened 2021-09-13 23:33 UTC by omarkasem

resolves #1638

2021-09-14 01:45 UTC, zackkatz requested changes

2021-09-14 01:45 UTC, zackkatz commented on includes/extensions/lightbox/fancybox/class-gravityview-lightbox-provider-fancybox.php
> +			Fancybox.bind(".gravityview-fancybox", <?php echo $settings; ?>);
@omarkasem There's always (_always_) some situation where a script doesn't load. Let's wrap in an `if ( window.Fancybox )` condition.

2021-09-14 01:45 UTC, zackkatz commented on includes/extensions/lightbox/fancybox/class-gravityview-lightbox-provider-fancybox.php
> +				// 'groupAll'=>true,
Why was this removed?

2021-09-14 01:45 UTC, zackkatz commented on includes/extensions/lightbox/fancybox/class-gravityview-lightbox-provider-fancybox.php
> +		wp_register_script( self::$script_slug, plugins_url( 'assets/lib/fancybox/dist/fancybox.umd.js', GRAVITYVIEW_FILE ), array( 'jquery' ), GV_PLUGIN_VERSION );
See my comment on Upwork—in the future, it'd just be good to know more about this type of change.

2021-09-14 17:49 UTC, omarkasem commented on includes/extensions/lightbox/fancybox/class-gravityview-lightbox-provider-fancybox.php
> +				// 'groupAll'=>true,
It was added by mistake while testing for duplicated image isssue

2021-09-14 19:47 UTC, zackkatz commented
@omarkasem Sorry for not clarifying; I meant those comments would be great in the commit messages, not as inline comments.

To explain the changes to future developers.

2021-09-17 16:37 UTC, mrcasual commented
@omarkasem I could not open PDF & text files. They work on `develop`.

2021-09-17 17:34 UTC, zackkatz commented
@omarkasem File types that open in an iframe have `gv-iframe=true` added to the URL, which is then processed here:
https://github.com/gravityview/GravityView/blob/af844d988d6088209bf6f62fed2e4a9f84ce8220/includes/extensions/lightbox/fancybox/class-gravityview-lightbox-provider-fancybox.php#L161-L171

2021-10-08 01:32 UTC, zackkatz commented
Closed, since already merged with `develop`. Going to manually cherry-pick b7823a75b8b38ad5e347f04ddccba9d7c27e474f

2021-10-08 01:32 UTC, closed without merging