Issue/1678 disable show only approved setting
gravityview/GravityView pull request #1685
Opened 2022-02-17 19:10 UTC by rafaehlers

Implements: https://github.com/gravityview/GravityView/issues/1678 by removing an existing link to the View editor and including a link that disables the "Show approved only" setting.

2022-02-17 19:59 UTC, zackkatz requested changes
Nice start!

2022-02-17 19:59 UTC, zackkatz commented on languages/gravityview-da.po
> +# Vlad K. <vlad@gravityview.co>, 2022
@rafaehlers When doing a PR, it's nice to include only the files that are relevant to the PR. It doesn't always work out that way, but just FYI.

2022-02-17 19:59 UTC, zackkatz commented on future/includes/class-gv-renderer.php
> +		// Disable this setting, hence displaying all entries on the View
Having this logic inside the `maybe_print_entry_approval_notice()` makes it so that the method no longer does what it says it does; it does two things.

Please refactor this out into its own method.

2022-02-17 19:59 UTC, zackkatz commented on future/includes/class-gv-renderer.php
> +			if( wp_redirect( home_url( $wp->request ), 302 ) ) {
This may be too late to redirect; when it's in its own method, it can be called earlier, which would reduce the chance of a failed redirect.

The `template_redirect` is a good hook to use.

2022-02-17 19:59 UTC, zackkatz commented on future/includes/class-gv-renderer.php
> +			if( wp_redirect( home_url( $wp->request ), 302 ) ) {
When redirecting back to an existing site, it's even better to use `wp_safe_redirect()` to prevent redirecting outside the current site.

2022-02-18 20:37 UTC, rafaehlers commented on languages/gravityview-da.po
> +# Vlad K. <vlad@gravityview.co>, 2022
@zackkatz I'll check how that's done in the GitHub app. I wasn't aware of this.

2022-02-18 20:39 UTC, rafaehlers commented on future/includes/class-gv-renderer.php
> +			if( wp_redirect( home_url( $wp->request ), 302 ) ) {
I started using that, but for some reason, I reverted back to wp_redirect. Okay, I'll change that.

2022-03-31 23:36 UTC, rafaehlers commented on future/includes/class-gv-renderer.php
> +			if( wp_redirect( home_url( $wp->request ), 302 ) ) {
I'm not sure where to use that hook (`template_redirect`) in this situation.

2022-05-04 19:16 UTC, zackkatz approved these changes
@rafaehlers Nice job with the usage of `_n()` translations, nonce links, `esc_html_x()`, and more.

2022-05-05 01:20 UTC, merged