Feature/1603 approve link mail
gravityview/GravityView pull request #1742
Opened 2022-09-02 19:15 UTC by pauloiankoski

The initial proposal for issue #1603 

Todos:
- Implement per-form setting to control redirect URL;
- Check conflict with merge tag having two modifiers being stripped out before replacing function;

2022-09-02 19:54 UTC, zackkatz requested changes
@pauloiankoski Thank you! Very good work 👍

This is some feedback from a first pass. Please let me know if you have any questions about my feedback.

2022-09-02 19:54 UTC, zackkatz commented on includes/class-gravityview-entry-approval-link.php
> +		$return_url = get_bloginfo( 'wpurl' ) . '/wp-admin/admin.php?page=gf_entries&id=' . $form_id;
Use `admin_url()` instead

2022-09-02 19:54 UTC, zackkatz commented on includes/class-gravityview-entry-approval-link.php
> +		wp_redirect( esc_url( $return_url ) );
Since this should always be the same site, we can use `wp_safe_redirect()`

2022-09-02 19:54 UTC, zackkatz commented on includes/class-gravityview-entry-approval-link.php
> +			$query_args['gv_token'] = $token;
`$query_args` isn't defined yet

2022-09-02 19:54 UTC, zackkatz commented on includes/class-gravityview-entry-approval-link.php
> +			$expiration_hours = 24;
Again, set as a class constant instead of inline definitions.

2022-09-02 19:54 UTC, zackkatz commented on includes/class-gravityview-entry-approval-link.php
> +			$secret = wp_generate_password( 64 );
`wp_generate_password()` can not be secure; it has a filter, so it can be made very weak if a developer is either being either malicious or lazy.

Instead, let's generate a more cryptographically-sound hash.

```
$byte_length = 128;

if ( function_exists( 'random_bytes' ) ) {
	try {
		return bin2hex( random_bytes( $byte_length ) ); // phpcs:ignore
	} catch ( \Exception $e ) {
	}
}

if ( function_exists( 'openssl_random_pseudo_bytes' ) ) {
	$crypto_strong = false;

	$bytes = openssl_random_pseudo_bytes( $byte_length, $crypto_strong );
	if ( true === $crypto_strong ) {
		return bin2hex( $bytes );
	}
}
```

2022-09-02 19:54 UTC, zackkatz commented on includes/class-gravityview-entry-approval-link.php
> +			update_option( 'gravityview_token_secret', $secret );
Let's set the `autoload` third parameter to false

2022-09-02 19:54 UTC, zackkatz commented on includes/class-gravityview-entry-approval-link.php
> +			$link = sprintf( '<a href="%s">%s</a>', esc_url( $link_url ), ucfirst( $action ) );
Using the regex to match the action then upper-casing it is smart, but it prevents it from being translated. Please replace with translatable text.

2022-09-02 19:54 UTC, zackkatz commented on includes/class-gravityview-entry-approval-link.php
> +			list( $full_tag, $action, $expiration_hours, $privacy ) = $match;
It's sometimes hard to see the `list()` function; please add a docblock with information about the variables that are being set.

2022-09-02 19:54 UTC, zackkatz commented on includes/class-gravityview-entry-approval-link.php
> +			$result = new WP_Error( 'invalid_status', __( 'The request was invalid. Refresh the page and try again.', 'gravityview' ) );
Where there's a `WP_Error`, let's return early and redirect out of the method. The `$return_url` doesn't change if there's an error; they can be defined at the top of the method and redirect.

2022-09-02 19:54 UTC, zackkatz commented on includes/class-gravityview-entry-approval-link.php
> +
Let's add a check for both and return early if possible.

2022-09-02 19:54 UTC, zackkatz commented on includes/class-gravityview-entry-approval-link.php
> +				return false;
No need to return false, since inside an action.

2022-09-02 19:54 UTC, zackkatz commented on includes/class-gravityview-entry-approval-link.php
> +				return false;
Same here: No need to return false, since inside an action.

2022-09-02 19:54 UTC, zackkatz commented on includes/class-gravityview-entry-approval-link.php
> +				return false;
Same here: No need to return false, since inside an action.

2022-09-02 19:54 UTC, zackkatz commented on includes/class-gravityview-entry-approval-link.php
> +		if ( GV\Utils::_GET( 'gv_approval_link_result' ) ) {
I think I'd actually like to break these into two additional methods—something like `maybe_update_approved` and `maybe_show_approval_notice`. That way it's clearer than doing both in one init.

2022-09-02 19:54 UTC, zackkatz commented on includes/class-gravityview-entry-approval-link.php
> +		if ( 24 > $token['scopes']['expiration_hours'] ) {
Use class constant instead of inline `24`.

2022-09-07 22:55 UTC, mrcasual commented
👋 @pauloiankoski 

A couple of comments:

1) I couldn't find the `per-form setting to enable public modifier`; apologies if it's due to my inattentiveness

2) Links with `:public` modifier prompt me to log in

3) There's an `array to string conversion` notice when trying to approve the link that has expired

<img width="759" alt="CleanShot 2022-09-21 at 20 20 24@2x" src="https://user-images.githubusercontent.com/2430296/188997211-d76310f7-6c6a-4da7-a63a-2897bcd996a7.png">

4) When submitting a form, I get a number of `undefined offset` notices:

<img width="1032" alt="CleanShot 2022-09-07 at 18 17 54@2x" src="https://user-images.githubusercontent.com/2430296/188997359-a7d871d9-1d50-4df7-ba12-ccecee356063.png">

2022-09-07 23:18 UTC, pauloiankoski commented
Thanks for your comments, @mrcasual! I'll work on those points then let you know.

2022-09-07 23:34 UTC, mrcasual commented on includes/class-gravityview-entry-approval-link.php
> +	}
What if neither of the 2 functions exists?

2022-09-07 23:34 UTC, mrcasual commented on includes/class-gravityview-entry-approval-link.php
> +	 *
Missing docblock.

2022-09-07 23:34 UTC, mrcasual commented on includes/class-gravityview-entry-approval-link.php
> +	 * Returns an approval status based on the provided action
Third-person or first-person singular? Choose one and stick with it. WP recommends third-person (e.g., "Returns...").

2022-09-07 23:34 UTC, mrcasual commented on includes/class-gravityview-entry-approval-link.php
> +			list( $full_tag, $action, $expiration_hours, $privacy ) = $match;
If the merge tag does not have expiration hours and privacy modifiers, `list` will result in a notice.

2022-09-07 23:34 UTC, mrcasual commented on includes/class-gravityview-entry-approval-link.php
> +		if ( is_wp_error( $result ) ) {
`GravityView_Entry_Approval::update_approved()` returns a `boolean`.

2022-09-07 23:34 UTC, mrcasual commented on includes/class-gravityview-entry-approval-link.php
> +		if ( is_wp_error( $result ) ) {
```php
if ( is_wp_error( $result ) ) {

	$return_url = add_query_arg( array( 'gv_approval_link_result' => 'error' ), $return_url );

} else {

	$return_url = add_query_arg( array( 'gv_approval_link_result' => 'success' ), $return_url );

}
```

...can be written as:

```php

$return_url = add_query_arg( array( 'gv_approval_link_result' => $result ? 'success' : 'error' ), $return_url );

```

2022-09-08 19:22 UTC, pauloiankoski commented
Hi @mrcasual 👋🏻!

1. Added the per-form setting. That's the setting that rules it all. In case it has not been changed, so the global setting will be used instead.
2. Could you confirm the global setting was enabled by the time the link was sent by mail?
3. and 4. were fixed as all the other comments.

Please let me know if you think anything else can be improved.

2022-09-10 14:22 UTC, mrcasual commented
@pauloiankoski, thanks for the changes. I left a couple of comments + this:

https://user-images.githubusercontent.com/2430296/189487571-22764a74-6b83-4215-99f9-a396fb47513b.mp4

2022-09-10 21:34 UTC, pauloiankoski commented
@mrcasual, in fact, it was requiring login but that was due to the redirect after updating the approval status. Changed to redirect the user to the home page when using the `:public` modifier.

2022-09-10 21:41 UTC, mrcasual requested changes

2022-09-12 23:19 UTC, mrcasual commented
@pauloiankoski public approval is working now.

A couple of additional findings:

1. A notice is displayed when changing the approval status using a merge tag with the `public` modifier:

<img width="1356" alt="CleanShot 2022-09-12 at 18 58 25@2x" src="https://user-images.githubusercontent.com/2430296/189772791-846e8b5a-bca2-4ddf-a649-d2cd5acda095.png">

 - We need to figure out a better placement. @zackkatz, thoughts?
 - Why is this notice **not** displayed in the admin panel when the `public` modifier is not used?
 - An expired link leads to a `Security check failed` notice, which ideally should read `The link has expired`.

2. I disabled both the global and per-form setting that disallows the `public` modifier and was still able to approve/disapprove entries using the previously generated link. Unless intentional, we should disallow this.

2023-01-12 02:39 UTC, merged