Issue/1217 add options when no entries in view
gravityview/GravityView pull request #1810
Opened 2023-02-06 09:45 UTC by omarkasem

- Added 3 options in multiple entries view settings
- Show message, Show form and redirect to url

2023-02-06 17:59 UTC, zackkatz requested changes

2023-02-06 17:59 UTC, zackkatz commented on includes/class-api.php
> +	return apply_filters('gravityview/template/no_entries',GravityView_API::no_results( $wpautop, $context ),$context);
@omarkasem The `GravityView_API::no_results()` method already has a `gravityview/template/text/no_entries` filter. That should be used.

2023-02-06 17:59 UTC, zackkatz commented on future/includes/class-gv-settings-view.php
> +					'options'           => ( new self() )->get_forms(),
This should be a static method instead.

2023-02-06 17:59 UTC, zackkatz commented on future/includes/class-gv-settings-view.php
> +	private function get_forms() {
- This should be in `GVCommon`
- Use `GFAPI::get_forms()` instead

2023-02-06 17:59 UTC, zackkatz commented on future/includes/class-gv-settings-view.php
> +					'tooltip'           => __( 'Incase the forms has no entries, You can show message or form or redirect to a URL.', 'gk-gravityview' ),
- Move to `desc` instead of `tooltip`
- Please ask us for text to use when adding labels and descriptions

2023-02-06 17:59 UTC, zackkatz commented on future/includes/class-gv-settings-view.php
> +					'tooltip'           => __( 'Show a Gravity form if there are no entries to show in the view.', 'gk-gravityview' ),
Move to `desc` instead of `tooltip`

2023-02-06 17:59 UTC, zackkatz commented on includes/class-frontend-views.php
> +	 * @param object $context
`\GV\Template_Context` type

2023-02-06 17:59 UTC, zackkatz commented on includes/class-frontend-views.php
> +	 * Fires when there are no entries in the view.
The "View" CPT is always capitalized to differentiate from the verb "view"

2023-02-06 17:59 UTC, zackkatz commented on includes/class-frontend-views.php
> +		$no_entries_option = intval( $context->view->settings->get( 'no_entries_options' ) );
Use `(int)` to cast instead of `intval()`—it removes a layer of nesting.

2023-02-06 17:59 UTC, zackkatz commented on includes/class-frontend-views.php
> +				return \GFForms::get_form( $form_id );
Use `GFAPI::get_form()` instead

2023-02-06 17:59 UTC, zackkatz commented on includes/class-frontend-views.php
> +			$form_id = intval( $context->view->settings->get( 'no_entries_form' ) );
`(int)`

2023-02-06 17:59 UTC, zackkatz commented on includes/class-frontend-views.php
> +				die();
We use `exit()` instead of `die()`

2023-02-08 04:29 UTC, omarkasem commented on includes/class-api.php
> +	return apply_filters('gravityview/template/no_entries',GravityView_API::no_results( $wpautop, $context ),$context);
@zackkatz Yeah I tried that one but the `wpautop` function at the end messed up the gravity form styling that's why I made the new filter.

2023-02-08 04:49 UTC, omarkasem commented on future/includes/class-gv-settings-view.php
> +					'tooltip'           => __( 'Incase the forms has no entries, You can show message or form or redirect to a URL.', 'gk-gravityview' ),
@zackkatz Should I leave them empty for you add them later in the PR or send a message first?

2023-02-08 15:43 UTC, zackkatz commented on future/includes/class-gv-settings-view.php
> +					'tooltip'           => __( 'Incase the forms has no entries, You can show message or form or redirect to a URL.', 'gk-gravityview' ),
@omarkasem A placeholder is great, but let us know. Please:

1. Add placeholder text
2. Ping us with a list of strings to review

2023-02-09 01:48 UTC, zackkatz commented on includes/class-api.php
> +	return apply_filters('gravityview/template/no_entries',GravityView_API::no_results( $wpautop, $context ),$context);
I modified the filter behavior to get around this in a7aec5bae

If you need another filter or need some breaking changes (like I just did), let me know. We prefer not to add filters if we have others that could work.

2023-02-09 01:48 UTC, zackkatz approved these changes

2023-02-09 21:39 UTC, zackkatz commented
@mrcasual In addition to a general review, please specifically review the changes to the template files and CSS class names.

Since forever, the `gv-no-results` class has centered text. If people have customized that, I didn't want to affect their output. So I add a class and modified the template files instead.

2023-02-13 16:15 UTC, merged